### ISSUE TITLE
onl mount missing 'device' key

### ISSUE THREAD

**Issue by twowen** [dentproject/dentOS#299]
==========================================================
ubinfo: error!: cannot get information about volume "ONL-IMAGES" on ubi0
        error 2 (No such file or directory)
ubinfo: error!: cannot get information about volume "ONL-DATA" on ubi0
        error 2 (No such file or directory)
ubinfo: error!: cannot get information about volume "ONL-BOOT" on ubi0
        error 2 (No such file or directory)
ubinfo: error!: cannot get information about volume "ONL-CONFIG" on ubi0
        error 2 (No such file or directory)
ERROR:onl-mounts:Timeout waiting for block label ONL-IMAGES after 5 seconds.
ERROR:onl-mounts:Timeout waiting for block label ONL-DATA after 5 seconds.
ERROR:onl-mounts:Timeout waiting for block label ONL-BOOT after 5 seconds.
ERROR:onl-mounts:Timeout waiting for block label ONL-CONFIG after 5 seconds.
ERROR:onl-mounts:Timeout waiting for block label EFI-BOOT after 5 seconds.
Traceback (most recent call last):
  File "/usr/bin/onl-mounts", line 3, in <module>
    OnlMountManager.main('onl-mounts')
  File "/usr/lib/python2.7/dist-packages/onl/mounts/__init__.py", line 422, in main
    ops.func(ops)
  File "/usr/lib/python2.7/dist-packages/onl/mounts/__init__.py", line 377, in cmdFsck
    o.fsck(args.labels, args.force)
  File "/usr/lib/python2.7/dist-packages/onl/mounts/__init__.py", line 302, in fsck
    if not self.mm.is_dev_mounted(m['device']):
KeyError: 'device'
ubinfo: error!: cannot get information about volume "ONL-IMAGES" on ubi0
        error 2 (No such file or directory)
ubinfo: error!: cannot get information about volume "ONL-DATA" on ubi0
        error 2 (No such file or directory)
ubinfo: error!: cannot get information about volume "ONL-BOOT" on ubi0
        error 2 (No such file or directory)
ubinfo: error!: cannot get information about volume "ONL-CONFIG" on ubi0

==========================================================

It looks like missing 'device' in the m dict which is generated from reading /proc/mounts,
I dump the m dict as below, we can found there was not any key named 'device' within the m dict.
{'ONL-IMAGES': {'mount': 'rw', 'dir': '/mnt/onl/images', 'fsck': True}, 'EFI-BOOT': {'mount': 'ro', 'fsck': False, 'optional': True, 'dir': '/boot/efi', 'label': 'EFI System'}, 'ONL-DATA': {'mount': 'rw', 'dir': '/mnt/onl/data', 'fsck': True}, 'ONL-BOOT': {'mount': 'rw', 'dir': '/mnt/onl/boot', 'fsck': True}, 'ONL-CONFIG': {'mount': 'ro', 'dir': '/mnt/onl/config', 'fsck': True}}

Or I need to edit mtab.yml by myself? Any ideas are welcome.

**Comment by twowen** [comment]
The issue is gone.
